version: '3.8'

services:
  # 1. LA BASE DE DATOS
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: 
      - .env  # <-- DOCKER LEERÁ TU ARCHIVO .ENV AQUÍ
    environment:
      # Postgres usa nombres específicos, así que los mapeamos desde tu .env
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  # 2. TU PROYECTO DJANGO
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
             
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # <-- LE PASAMOS EL .ENV A DJANGO
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  # 3. EL WORKER
  worker:
    build: .
    command: python manage.py sync_flespi 
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    env_file:
      - .env  # <-- LE PASAMOS EL .ENV AL WORKER
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  # 4. GRAFANA
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - db
  generador_datos:
    build: .  # Usa la misma imagen que tu web para tener Python y las librerías
    # Aquí pones el comando exacto que usas para correr el script
    command: >
      sh -c "python manage.py poblar_base && 
             python manage.py simular_viaje 123456789012345 & 
             python manage.py simular_viaje 987654321098765 & 
             wait"

    volumes:
      - .:/app  # Mapea tus archivos para que lea el script actualizado
    depends_on:
      - db
      - web
    # Si tu script necesita conectarse a la DB o a la API, 
    # pásale las mismas variables de entorno que tiene tu servicio web:
    env_file:
      - .env


volumes:
  postgres_data:

