version: '3.8'

services:
  # 1. LA BASE DE DATOS
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  # 2. TU PROYECTO DJANGO (Modo Desarrollo)
  web:
    build: .
    # TRUCO 1: Entramos como root para que los volúmenes no den error de permisos
    user: "root" 
    # TRUCO 2: Ignoramos el Gunicorn de producción y usamos el servidor de desarrollo
    command: >
      sh -c "python manage.py migrate &&
            python manage.py poblar_base && 
             python manage.py poblar_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # <-- Tus volúmenes intactos para programar en vivo
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  # 3. EL WORKER
  worker:
    build: .
    user: "root" # Mismo truco de permisos
    command: python manage.py sync_flespi 
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  # 4. GRAFANA
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - db

  # 5. GENERADOR DE DATOS
  generador_datos:
    build: .
    user: "root" # Mismo truco de permisos
    command: >
      sh -c "
             python manage.py simular_viaje 123456789012345 & 
             python manage.py simular_viaje 987654321098765 & 
             wait"
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    env_file:
      - .env
      


volumes:
  postgres_data: